#variables:
#  KUBE_NAMESPACE: default

stages:
  - build
  - package
  - deploy
  
maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - cd springboot-k8s-mongo
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
      - springboot-k8s-mongo/target/*.jar

docker-build:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  before_script:
    - docker login -u "prabhavi" -p "Ilovemc1992"
  script:
    - cd springboot-k8s-mongo
    - docker build  -t "prabhavi/springboot-k8s-mongo" .
    - docker push "prabhavi/springboot-k8s-mongo"

deploy:
  image: google/cloud-sdk
  stage: deploy
  environment:
    name: production
  script:
    - cd springboot-k8s-mongo
    - kubectl apply -f springboot-dep-blue-v1.yml
    - kubectl apply -f springboot-dep-green-v2.yml
    - kubectl apply -f springboot-svc-blue-v1.yml
    - kubectl apply -f springboot-svc-green-v2.yml
    - kubectl get pods
    - kubectl get svc
    - echo done
