---
kind: Service
apiVersion: v1
metadata:
  name: spring-mongo-service
  labels:
        version:"v2"
spec:
  selector:
    app: spring-mongo-service
  ports:
  - name: http 
    port: 8080
  type: LoadBalancer

