---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo-service-v2
spec:
  selector:
      matchLabels:
        app: spring-mongo-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spring-mongo-service
        version: "v2"
    spec:
      containers:
        - name: spring-mongo-service
          image: prabhavi/springboot-k8s-mongo:v2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf 
                  key: host
                  
